# Generated by Django 5.0.1 on 2024-03-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='shoe_id',
            new_name='id',
        ),
    ]
