# Generated by Django 5.0.1 on 2024-03-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0002_rename_shoe_id_shoe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
